"""Constants for identity system (RFC-023)."""

# Constants from RFC-023
MIN_IDENTITY_CONFIDENCE = 0.6
MAX_OBSERVATIONS_PER_SESSION = 50
MAX_OBSERVATIONS_GLOBAL = 100
MAX_IDENTITY_PROMPT_LENGTH = 500
