"""Core domain models for Sunwell."""

from sunwell.core.context.context import AppContext
from sunwell.core.models import (
    AntiHeuristic,
    CommunicationStyle,
    DeterministicValidator,
    Framework,
    FrameworkCategory,
    Grimoire,
    Heuristic,
    HeuristicValidator,
    Persona,
    Reagent,
    ReagentMode,
    ReagentType,
    Refiner,
    SchemaValidationMethod,
    SchemaValidator,
    Spell,
    SpellExample,
    SpellResult,
    SpellValidation,
    ValidationMode,
    ValidationResult,
    Workflow,
    WorkflowStep,
    parse_spell,
    validate_spell_output,
)
from sunwell.core.types import (
    Confidence,
    IntentCategory,
    LensReference,
    SemanticVersion,
    Severity,
    Tier,
    ValidationMethod,
)
from sunwell.foundation.threading import (
    WorkloadType,
    is_free_threaded,
    optimal_workers,
    run_cpu_bound,
    run_parallel,
    run_parallel_async,
    runtime_info,
)
from sunwell.foundation.identity import (
    ResourceIdentity,
    SunwellURI,
    URIParseError,
    slugify,
    validate_slug,
)
from sunwell.foundation.core.lens import Lens, LensMetadata

__all__ = [
    "Lens",
    "LensMetadata",
    "Heuristic",
    "AntiHeuristic",
    "CommunicationStyle",
    "Persona",
    "DeterministicValidator",
    "HeuristicValidator",
    "SchemaValidator",
    "SchemaValidationMethod",
    "ValidationResult",
    "Framework",
    "FrameworkCategory",
    "Workflow",
    "WorkflowStep",
    "Refiner",
    "Severity",
    "Tier",
    "ValidationMethod",
    "IntentCategory",
    "SemanticVersion",
    "LensReference",
    "Confidence",
    # Free-threading utilities
    "is_free_threaded",
    "optimal_workers",
    "WorkloadType",
    "run_parallel",
    "run_parallel_async",
    "run_cpu_bound",
    "runtime_info",
    # Spells (RFC-021)
    "Spell",
    "SpellValidation",
    "SpellExample",
    "Reagent",
    "ReagentType",
    "ReagentMode",
    "ValidationMode",
    "Grimoire",
    "SpellResult",
    "parse_spell",
    "validate_spell_output",
    # Context (RFC-025)
    "AppContext",
    # Identity (RFC-101)
    "SunwellURI",
    "ResourceIdentity",
    "URIParseError",
    "slugify",
    "validate_slug",
]
