"""Model delegation event factories (RFC-137).

Event factories for smart-to-dumb model delegation:
- delegation_started_event: Delegation initiated
- ephemeral_lens_created_event: EphemeralLens generated
"""

from typing import Any

from sunwell.agent.events.types import AgentEvent, EventType


def delegation_started_event(
    task_description: str,
    smart_model: str,
    delegation_model: str,
    reason: str,
    estimated_tokens: int = 0,
    **kwargs: Any,
) -> AgentEvent:
    """Create a delegation started event (RFC-137).

    Emitted when smart-to-dumb model delegation is initiated.

    Args:
        task_description: What task is being delegated
        smart_model: Model used for lens creation (e.g., "claude-3-opus")
        delegation_model: Model used for execution (e.g., "claude-3-haiku")
        reason: Why delegation was chosen
        estimated_tokens: Estimated output tokens for this task
    """
    return AgentEvent(
        EventType.DELEGATION_STARTED,
        {
            "task_description": task_description[:200],
            "smart_model": smart_model,
            "delegation_model": delegation_model,
            "reason": reason,
            "estimated_tokens": estimated_tokens,
            **kwargs,
        },
    )


def ephemeral_lens_created_event(
    task_scope: str,
    heuristics_count: int,
    patterns_count: int,
    generated_by: str,
    anti_patterns_count: int = 0,
    constraints_count: int = 0,
    **kwargs: Any,
) -> AgentEvent:
    """Create an ephemeral lens created event (RFC-137).

    Emitted when an EphemeralLens has been generated by the smart model.

    Args:
        task_scope: Brief description of what the lens covers
        heuristics_count: Number of heuristics in the lens
        patterns_count: Number of patterns to follow
        generated_by: Model that generated the lens
        anti_patterns_count: Number of anti-patterns to avoid
        constraints_count: Number of hard constraints
    """
    return AgentEvent(
        EventType.EPHEMERAL_LENS_CREATED,
        {
            "task_scope": task_scope[:100],
            "heuristics_count": heuristics_count,
            "patterns_count": patterns_count,
            "anti_patterns_count": anti_patterns_count,
            "constraints_count": constraints_count,
            "generated_by": generated_by,
            **kwargs,
        },
    )
