"""Features domain - Opt-in specialized capabilities.

This domain consolidates optional features that don't fit in core domains.

RFC-138: Module Architecture Consolidation
"""

# Vortex - Multi-model coordination
# Autonomous - Autonomous execution
from sunwell.features.autonomous import (
    AutonomousConfig,
    AutonomousState,
    autonomous_goal,
    resume_autonomous,
)

# Backlog - Autonomous backlog
from sunwell.features.backlog import (
    AutonomousLoop,
    Backlog,
    BacklogManager,
    DictSerializable,
    EpicDecomposer,
    Goal,
    GoalGenerator,
    GoalPolicy,
    GoalResult,
    GoalScope,
    LearningStore,
    MilestoneLearning,
    MilestoneProgress,
    MilestoneTracker,
    ObservableSignal,
    SignalExtractor,
)

# External - External integrations
from sunwell.features.external import (
    EventCallback,
    EventFeedback,
    EventProcessor,
    EventSource,
    EventType,
    ExternalContext,
    ExternalEvent,
    ExternalEventStore,
    ExternalGoalPolicy,
    RateLimitBucket,
    RateLimiter,
)

# External Integration - Integration-aware DAG
from sunwell.features.external.integration import (
    ArtifactDefinition,
    IntegrationAwareGoal,
    IntegrationCheck,
    IntegrationCheckType,
    IntegrationDefinition,
    IntegrationResult,
    IntegrationType,
    IntegrationVerificationSummary,
    IntegrationVerifier,
    OrphanDetection,
    ProducedArtifact,
    RequiredIntegration,
    StubDetection,
    TaskType,
    create_frontend_api_wire_task,
    create_route_registration_task,
    create_verify_task,
    create_wire_task,
    decompose_with_wiring,
)

# Fount - Lens distribution
from sunwell.features.fount import FountCache, FountClient, LensResolver

# Mirror - Self-introspection and self-programming
from sunwell.features.mirror import (
    MIRROR_TOOL_TRUST,
    MIRROR_TOOLS,
    TASK_CATEGORY_MAP,
    FailureAnalyzer,
    MirrorHandler,
    ModelPerformanceEntry,
    ModelPerformanceTracker,
    ModelRouter,
    ModelRoutingConfig,
    Proposal,
    ProposalManager,
    ProposalStatus,
    ProposalType,
    SafetyChecker,
    SafetyPolicy,
    SourceIntrospector,
    analyze_errors,
    analyze_latency,
    analyze_tool_usage,
    execution_get_error_summary,
    execution_get_errors,
    execution_get_recent_tool_calls,
    execution_get_stats,
    get_all_task_categories,
    get_mirror_tools_for_trust,
    get_tools_for_category,
    lens_get_all,
    lens_get_framework,
    lens_get_heuristics,
    lens_get_personas,
    lens_get_validators,
    simulacrum_get_all,
    simulacrum_get_context,
    simulacrum_get_dead_ends,
    simulacrum_get_focus,
    simulacrum_get_learnings,
    validate_diff_safety,
)

# Mirror Self - Self-knowledge architecture
from sunwell.features.mirror.self import Self

# Team - Team intelligence
from sunwell.features.team import (
    SUNWELL_GITIGNORE,
    ApproachCheck,
    ApproachWarning,
    ConflictResolver,
    Embeddable,
    FileContext,
    KnowledgeConflict,
    KnowledgePropagator,
    KnowledgeScope,
    OnboardingSummary,
    RejectedOption,
    Serializable,
    SyncResult,
    TeamConfig,
    TeamDecision,
    TeamFailure,
    TeamKnowledgeContext,
    TeamKnowledgeStore,
    TeamKnowledgeUpdate,
    TeamOnboarding,
    TeamOwnership,
    TeamPatterns,
    UnifiedIntelligence,
    create_sunwell_gitignore,
    ensure_sunwell_structure,
)
from sunwell.features.vortex import (
    FAST_CONFIG,
    QUALITY_CONFIG,
    DialecticResult,
    GradientResult,
    InterferenceResult,
    Island,
    LocalityResult,
    ResonanceResult,
    Signal,
    Subtask,
    Vortex,
    VortexConfig,
    VortexResult,
    dialectic,
    evolve_islands,
    format_result,
    format_signal,
    gradient,
    interference,
    resonance,
    solve,
)

# Workflow - Workflow execution
from sunwell.features.workflow import (
    Intent,
    IntentCategory,
    IntentRouter,
    WorkflowChain,
    WorkflowEngine,
    WorkflowExecution,
    WorkflowResult,
    WorkflowState,
    WorkflowStateManager,
    WorkflowStep,
    WorkflowStepResult,
    WorkflowTier,
)

__all__ = [
    # Vortex
    "Vortex",
    "VortexResult",
    "solve",
    "format_result",
    "VortexConfig",
    "FAST_CONFIG",
    "QUALITY_CONFIG",
    "Signal",
    "format_signal",
    "Island",
    "LocalityResult",
    "evolve_islands",
    "InterferenceResult",
    "DialecticResult",
    "ResonanceResult",
    "GradientResult",
    "Subtask",
    "interference",
    "dialectic",
    "resonance",
    "gradient",
    # Mirror
    "SourceIntrospector",
    "lens_get_all",
    "lens_get_framework",
    "lens_get_heuristics",
    "lens_get_personas",
    "lens_get_validators",
    "simulacrum_get_all",
    "simulacrum_get_context",
    "simulacrum_get_dead_ends",
    "simulacrum_get_focus",
    "simulacrum_get_learnings",
    "execution_get_error_summary",
    "execution_get_errors",
    "execution_get_recent_tool_calls",
    "execution_get_stats",
    "analyze_errors",
    "analyze_latency",
    "analyze_tool_usage",
    "FailureAnalyzer",
    "Proposal",
    "ProposalStatus",
    "ProposalType",
    "ProposalManager",
    "MirrorHandler",
    "MIRROR_TOOLS",
    "MIRROR_TOOL_TRUST",
    "get_mirror_tools_for_trust",
    "ModelPerformanceTracker",
    "ModelPerformanceEntry",
    "ModelRouter",
    "ModelRoutingConfig",
    "TASK_CATEGORY_MAP",
    "get_all_task_categories",
    "get_tools_for_category",
    "SafetyChecker",
    "SafetyPolicy",
    "validate_diff_safety",
    # Mirror Self
    "Self",
    # Fount
    "FountClient",
    "FountCache",
    "LensResolver",
    # Team
    "Serializable",
    "Embeddable",
    "KnowledgeScope",
    "RejectedOption",
    "TeamDecision",
    "TeamFailure",
    "TeamPatterns",
    "TeamOwnership",
    "TeamKnowledgeContext",
    "TeamKnowledgeUpdate",
    "TeamKnowledgeStore",
    "SyncResult",
    "ConflictResolver",
    "KnowledgeConflict",
    "KnowledgePropagator",
    "UnifiedIntelligence",
    "ApproachCheck",
    "ApproachWarning",
    "FileContext",
    "TeamOnboarding",
    "OnboardingSummary",
    "TeamConfig",
    "SUNWELL_GITIGNORE",
    "create_sunwell_gitignore",
    "ensure_sunwell_structure",
    # External
    "EventSource",
    "EventType",
    "ExternalEvent",
    "EventFeedback",
    "EventCallback",
    "ExternalGoalPolicy",
    "RateLimiter",
    "RateLimitBucket",
    "EventProcessor",
    "ExternalEventStore",
    "ExternalContext",
    # External Integration
    "ProducedArtifact",
    "RequiredIntegration",
    "IntegrationCheck",
    "IntegrationResult",
    "StubDetection",
    "OrphanDetection",
    "IntegrationVerificationSummary",
    "IntegrationType",
    "IntegrationCheckType",
    "TaskType",
    "IntegrationAwareGoal",
    "ArtifactDefinition",
    "IntegrationDefinition",
    "IntegrationVerifier",
    "decompose_with_wiring",
    "create_wire_task",
    "create_verify_task",
    "create_route_registration_task",
    "create_frontend_api_wire_task",
    # Backlog
    "ObservableSignal",
    "SignalExtractor",
    "Goal",
    "GoalGenerator",
    "GoalPolicy",
    "GoalResult",
    "GoalScope",
    "Backlog",
    "BacklogManager",
    "AutonomousLoop",
    "EpicDecomposer",
    "MilestoneTracker",
    "MilestoneProgress",
    "MilestoneLearning",
    "LearningStore",
    "DictSerializable",
    # Autonomous
    "AutonomousConfig",
    "AutonomousState",
    "autonomous_goal",
    "resume_autonomous",
    # Workflow
    "WorkflowEngine",
    "WorkflowResult",
    "IntentRouter",
    "WorkflowState",
    "WorkflowStateManager",
    "Intent",
    "IntentCategory",
    "WorkflowChain",
    "WorkflowExecution",
    "WorkflowStep",
    "WorkflowStepResult",
    "WorkflowTier",
]
