"""Type-safe event schemas using Python's type system.

DEPRECATED: This module is maintained for backward compatibility.
New code should import from `sunwell.agent.events.schemas` instead.

This module provides TypedDict schemas for each event type, ensuring
type safety and validation at both Python and TypeScript boundaries.

Migration guide:
    # Old (still works)
    from sunwell.agent.event_schema import PlanStartData, create_validated_event

    # New (preferred)
    from sunwell.agent.events.schemas import PlanStartData, create_validated_event
"""

# Re-export everything from the new modular structure for backward compatibility
from sunwell.agent.events.schemas import (
    # Registry
    EVENT_SCHEMAS,
    REQUIRED_FIELDS,
    # Protocols
    EventEmitter,
    ValidatedEventEmitter,
    # Validation functions
    validate_event_data,
    create_validated_event,
    get_validation_mode,
    # Factory functions
    validated_task_start_event,
    validated_task_complete_event,
    validated_task_failed_event,
    validated_plan_winner_event,
    # Base schemas
    PlanStartData,
    PlanWinnerData,
    TaskStartData,
    TaskProgressData,
    TaskCompleteData,
    TaskFailedData,
    MemoryLearningData,
    CompleteData,
    ErrorData,
    EscalateData,
    # Planning schemas
    PlanCandidateData,
    PlanExpandedData,
    PlanAssessData,
    PlanDiscoveryProgressData,
    # Harmonic schemas
    PlanCandidateStartData,
    PlanCandidateGeneratedData,
    PlanCandidatesCompleteData,
    PlanCandidateScoredData,
    PlanScoringCompleteData,
    # Refinement schemas
    PlanRefineStartData,
    PlanRefineAttemptData,
    PlanRefineCompleteData,
    PlanRefineFinalData,
    # Memory schemas
    MemoryLoadData,
    MemoryLoadedData,
    MemoryNewData,
    MemoryDeadEndData,
    MemoryCheckpointData,
    MemorySavedData,
    # Signal schemas
    SignalData,
    SignalRouteData,
    # Gate schemas
    GateStartData,
    GateStepData,
    GatePassData,
    GateFailData,
    # Validation schemas
    ValidateStartData,
    ValidateLevelData,
    ValidateErrorData,
    ValidatePassData,
    # Fix schemas
    FixStartData,
    FixProgressData,
    FixAttemptData,
    FixCompleteData,
    FixFailedData,
    # Lens schemas
    LensSelectedData,
    LensChangedData,
    LensSuggestedData,
    # Briefing schemas
    BriefingLoadedData,
    BriefingSavedData,
    # Prefetch schemas
    PrefetchStartData,
    PrefetchCompleteData,
    PrefetchTimeoutData,
    # Model schemas
    ModelStartData,
    ModelTokensData,
    ModelThinkingData,
    ModelCompleteData,
    ModelHeartbeatData,
    # Skill schemas
    SkillCompileStartData,
    SkillCompileCompleteData,
    SkillCompileCacheHitData,
    SkillSubgraphExtractedData,
    SkillGraphResolvedData,
    SkillWaveStartData,
    SkillWaveCompleteData,
    SkillCacheHitData,
    SkillExecuteStartData,
    SkillExecuteCompleteData,
    # Backlog schemas
    BacklogGoalAddedData,
    BacklogGoalStartedData,
    BacklogGoalCompletedData,
    BacklogGoalFailedData,
    BacklogRefreshedData,
    # Convergence schemas
    ConvergenceStartData,
    ConvergenceIterationStartData,
    ConvergenceIterationCompleteData,
    ConvergenceFixingData,
    ConvergenceStableData,
    ConvergenceTimeoutData,
    ConvergenceStuckData,
    ConvergenceMaxIterationsData,
    ConvergenceBudgetExceededData,
    # Recovery schemas
    RecoverySavedData,
    RecoveryLoadedData,
    RecoveryResolvedData,
    RecoveryAbortedData,
    # Integration schemas
    IntegrationCheckStartData,
    IntegrationCheckPassData,
    IntegrationCheckFailData,
    StubDetectedData,
    OrphanDetectedData,
    WireTaskGeneratedData,
    # Security schemas
    SecurityApprovalRequestedData,
    SecurityApprovalReceivedData,
    SecurityViolationData,
    SecurityScanCompleteData,
    AuditLogEntryData,
)

__all__ = [
    # Registry
    "EVENT_SCHEMAS",
    "REQUIRED_FIELDS",
    # Protocols
    "EventEmitter",
    "ValidatedEventEmitter",
    # Validation functions
    "validate_event_data",
    "create_validated_event",
    "get_validation_mode",
    # Factory functions
    "validated_task_start_event",
    "validated_task_complete_event",
    "validated_task_failed_event",
    "validated_plan_winner_event",
    # All TypedDict schemas (98 total)
    "PlanStartData",
    "PlanWinnerData",
    "TaskStartData",
    "TaskProgressData",
    "TaskCompleteData",
    "TaskFailedData",
    "MemoryLearningData",
    "CompleteData",
    "ErrorData",
    "EscalateData",
    "PlanCandidateData",
    "PlanExpandedData",
    "PlanAssessData",
    "PlanDiscoveryProgressData",
    "PlanCandidateStartData",
    "PlanCandidateGeneratedData",
    "PlanCandidatesCompleteData",
    "PlanCandidateScoredData",
    "PlanScoringCompleteData",
    "PlanRefineStartData",
    "PlanRefineAttemptData",
    "PlanRefineCompleteData",
    "PlanRefineFinalData",
    "MemoryLoadData",
    "MemoryLoadedData",
    "MemoryNewData",
    "MemoryDeadEndData",
    "MemoryCheckpointData",
    "MemorySavedData",
    "SignalData",
    "SignalRouteData",
    "GateStartData",
    "GateStepData",
    "GatePassData",
    "GateFailData",
    "ValidateStartData",
    "ValidateLevelData",
    "ValidateErrorData",
    "ValidatePassData",
    "FixStartData",
    "FixProgressData",
    "FixAttemptData",
    "FixCompleteData",
    "FixFailedData",
    "LensSelectedData",
    "LensChangedData",
    "LensSuggestedData",
    "BriefingLoadedData",
    "BriefingSavedData",
    "PrefetchStartData",
    "PrefetchCompleteData",
    "PrefetchTimeoutData",
    "ModelStartData",
    "ModelTokensData",
    "ModelThinkingData",
    "ModelCompleteData",
    "ModelHeartbeatData",
    "SkillCompileStartData",
    "SkillCompileCompleteData",
    "SkillCompileCacheHitData",
    "SkillSubgraphExtractedData",
    "SkillGraphResolvedData",
    "SkillWaveStartData",
    "SkillWaveCompleteData",
    "SkillCacheHitData",
    "SkillExecuteStartData",
    "SkillExecuteCompleteData",
    "BacklogGoalAddedData",
    "BacklogGoalStartedData",
    "BacklogGoalCompletedData",
    "BacklogGoalFailedData",
    "BacklogRefreshedData",
    "ConvergenceStartData",
    "ConvergenceIterationStartData",
    "ConvergenceIterationCompleteData",
    "ConvergenceFixingData",
    "ConvergenceStableData",
    "ConvergenceTimeoutData",
    "ConvergenceStuckData",
    "ConvergenceMaxIterationsData",
    "ConvergenceBudgetExceededData",
    "RecoverySavedData",
    "RecoveryLoadedData",
    "RecoveryResolvedData",
    "RecoveryAbortedData",
    "IntegrationCheckStartData",
    "IntegrationCheckPassData",
    "IntegrationCheckFailData",
    "StubDetectedData",
    "OrphanDetectedData",
    "WireTaskGeneratedData",
    "SecurityApprovalRequestedData",
    "SecurityApprovalReceivedData",
    "SecurityViolationData",
    "SecurityScanCompleteData",
    "AuditLogEntryData",
]
