"""Planning domain - Intent classification, routing, reasoning, planning, skills, lens management.

This domain consolidates all modules that handle intent → plan transformation.

RFC-138: Module Architecture Consolidation

Key components:
- Routing: Cognitive routing for intent-aware retrieval (UnifiedRouter)
- Reasoning: LLM-driven judgment over rule-based logic (Reasoner, FastClassifier)
- Naaru: Coordinated intelligence for local models (Naaru, Task, planners)
- Skills: Agent skills integration for Sunwell Lenses (Skill, SkillGraph, SkillCompiler)
- Lens: Lens management and library (LensManager, LensIndex)

Example:
    >>> from sunwell.planning import UnifiedRouter, Reasoner, Naaru
    >>> from sunwell.planning import Skill, SkillGraph, LensManager
    >>>
    >>> # Cognitive routing
    >>> router = UnifiedRouter(model)
    >>> decision = await router.route(request)
    >>>
    >>> # Reasoned decisions
    >>> reasoner = Reasoner(model)
    >>> decision = await reasoner.decide(DecisionType.SEVERITY_ASSESSMENT, context)
    >>>
    >>> # Coordinated planning
    >>> naaru = Naaru(...)
    >>> results = await naaru.illuminate(goals=["improve error handling"])
"""

# Routing
from sunwell.planning.routing import (
    DEFAULT_RUBRIC,
    INTENT_FOCUS_MAP,
    INTENT_LENS_MAP,
    LENS_NAME_MAP,
    ROUTING_EXEMPLARS,
    UNIFIED_ROUTER_PROMPT,
    Complexity,
    ConfidenceRubric,
    ExecutionTier,
    HasStats,
    Intent,
    RoutingDecision,
    RoutingExemplar,
    Serializable,
    TierBehavior,
    UserExpertise,
    UserMood,
    create_unified_router,
    determine_tier,
    match_exemplar,
    UnifiedRouter,
)

# Reasoning
from sunwell.planning.reasoning import (
    APPROVAL_OUTCOMES,
    BINARY_TEMPLATE,
    COMPLEXITY_TEMPLATE,
    CONFIDENCE_THRESHOLDS,
    DISPLAY_VARIANTS,
    INTENT_TEMPLATE,
    RECOVERY_STRATEGIES,
    RISK_TEMPLATE,
    SCORE_TEMPLATE,
    SEVERITY_LEVELS,
    SEVERITY_TEMPLATE,
    CalibrationRecord,
    CalibrationStats,
    ClassificationResult,
    ClassificationTemplate,
    ConfidenceCalibrator,
    ContextEnricher,
    DecisionType,
    FastClassifier,
    PromptBuilder,
    RecoveryDecision,
    ReasonedDecision,
    Reasoner,
    get_recommended_model,
)

# Naaru (coordinated intelligence)
from sunwell.planning.naaru import (
    AgentCheckpoint,
    AgentPlanner,
    AgentResult,
    AnalysisWorker,
    ArtifactCompletion,
    ArtifactCreationError,
    ArtifactError,
    ArtifactExecutor,
    ArtifactGraph,
    ArtifactLimits,
    ArtifactResult,
    ArtifactSpec,
    AutonomousRunner,
    Candidate,
    CandidateResult,
    CognitiveRoutingWorker,
    Convergence,
    CyclicDependencyError,
    Discernment,
    DiscernmentResult,
    DiscernmentVerdict,
    DiscoveryFailedError,
    EventEmitter,
    ExecutionCache,
    ExecutionCoordinator,
    ExecutionEvent,
    ExecutionPlan,
    ExecutionResult,
    ExecutionStatus,
    ExecutiveWorker,
    FailurePolicy,
    GraphExplosionError,
    HARMONIC_PERSONAS,
    HarmonicPlanner,
    HarmonicSynthesisWorker,
    IntegrationCheck,
    IntegrationCheckType,
    IntegrationResult,
    IntegrationType,
    IntegrationVerifier,
    IncrementalExecutorV2,
    IncrementalResult,
    LearningExtractor,
    MemoryWorker,
    MessageBus,
    MessageType,
    MissingDependencyError,
    MURU,
    ModelSize,
    Naaru,
    NaaruConfig,
    NaaruEventEmitter,
    NaaruMessage,
    NaaruPersona,
    NaaruRegion,
    Opportunity,
    OpportunityCategory,
    OpportunityDiscoverer,
    ParallelAutonomousRunner,
    ParallelConfig,
    ParallelismAnalysis,
    PlanMetrics,
    PlanMetricsV2,
    PlanStore,
    PlanningError,
    PlanningStrategy,
    RefinementAttempt,
    RefinementResult,
    RequiredIntegration,
    Resonance,
    ResonanceConfig,
    ResonanceResult,
    RiskLevel,
    SavedExecution,
    ScoringVersion,
    SelfImprovementPlanner,
    SessionConfig,
    SessionState,
    SessionStatus,
    Shard,
    ShardPool,
    ShardType,
    SignalHandler,
    SkipDecision,
    SkipReason,
    Slot,
    SlotSource,
    StopReason,
    StubDetection,
    Task,
    TaskAnalysis,
    TaskExecutionConfig,
    TaskMode,
    TaskPlanner,
    TaskStatus,
    TaskType,
    ToolRegionWorker,
    TraceLogger,
    UnifiedResult,
    ValidationWorker,
    VarianceStrategy,
    VerificationResult,
    WorkerStats,
    analyze_parallelism,
    artifact_to_task,
    artifacts_to_tasks,
    create_auto_config,
    create_balanced_config,
    create_cheap_diversity_config,
    create_minimal_config,
    create_quality_config,
    create_resonance_handler,
    diversity_harmonic,
    diversity_none,
    diversity_rotation,
    diversity_sampling,
    execute_artifact_graph,
    execute_with_discovery,
    find_latest_checkpoint,
    format_execution_summary,
    get_checkpoint_path,
    get_latest_execution,
    get_model_distribution,
    hash_content,
    hash_file,
    hash_goal,
    refine_full,
    refine_none,
    refine_tiered,
    resume_execution,
    save_execution,
    select_heuristic,
    select_judge,
    select_model_tier,
    select_passthrough,
    select_strategies,
    select_voting,
    unified_pipeline,
    validate_contracts,
    visualize_task_graph,
)

# Skills
from sunwell.planning.skills import (
    Artifact,
    CircularDependencyError,
    CompiledTaskGraph,
    ExecutionPattern,
    LearnedSkillMetadata,
    MissingDependencyError,
    Resource,
    Script,
    ScriptResult,
    ScriptSandbox,
    Skill,
    SkillCache,
    SkillCacheEntry,
    SkillCacheKey,
    SkillCompilationCache,
    SkillCompilationError,
    SkillCompiler,
    SkillDependency,
    SkillError,
    SkillExporter,
    SkillGraph,
    SkillGraphError,
    SkillImporter,
    SkillLearner,
    SkillLearningResult,
    SkillLibrary,
    SkillMetadata,
    SkillOutput,
    SkillOutputMetadata,
    SkillProvenance,
    SkillResult,
    SkillRetryPolicy,
    SkillType,
    SkillValidation,
    SkillValidationResult,
    Template,
    TrustLevel,
    UnsatisfiedRequiresError,
    has_dag_metadata,
    validate_skill_folder,
)

# Lens
from sunwell.planning.lens import (
    DictSerializable,
    LensIndex,
    LensIndexEntry,
    LensIndexManager,
    LensLibraryEntry,
    LensLineage,
    LensManifest,
    LensManager,
    LensVersionInfo,
    add_version_to_manifest,
    create_lens_manifest,
)

__all__ = [
    # Routing
    "HasStats",
    "Serializable",
    "Intent",
    "Complexity",
    "UserMood",
    "UserExpertise",
    "ExecutionTier",
    "TierBehavior",
    "determine_tier",
    "ConfidenceRubric",
    "DEFAULT_RUBRIC",
    "RoutingExemplar",
    "ROUTING_EXEMPLARS",
    "match_exemplar",
    "RoutingDecision",
    "UnifiedRouter",
    "create_unified_router",
    "UNIFIED_ROUTER_PROMPT",
    "LENS_NAME_MAP",
    "INTENT_LENS_MAP",
    "INTENT_FOCUS_MAP",
    # Reasoning
    "DecisionType",
    "ReasonedDecision",
    "RecoveryDecision",
    "Reasoner",
    "ContextEnricher",
    "PromptBuilder",
    "FastClassifier",
    "ClassificationResult",
    "ClassificationTemplate",
    "get_recommended_model",
    "ConfidenceCalibrator",
    "CalibrationRecord",
    "CalibrationStats",
    "SEVERITY_LEVELS",
    "RECOVERY_STRATEGIES",
    "DISPLAY_VARIANTS",
    "APPROVAL_OUTCOMES",
    "CONFIDENCE_THRESHOLDS",
    "SEVERITY_TEMPLATE",
    "COMPLEXITY_TEMPLATE",
    "INTENT_TEMPLATE",
    "RISK_TEMPLATE",
    "BINARY_TEMPLATE",
    "SCORE_TEMPLATE",
    # Naaru - Core Types
    "SessionStatus",
    "RiskLevel",
    "Opportunity",
    "OpportunityCategory",
    "SessionConfig",
    "SessionState",
    "Task",
    "TaskMode",
    "TaskStatus",
    "TaskType",
    "IntegrationType",
    "IntegrationCheckType",
    "RequiredIntegration",
    "IntegrationCheck",
    "IntegrationResult",
    # Naaru - Core Runners
    "AutonomousRunner",
    "OpportunityDiscoverer",
    "ParallelAutonomousRunner",
    "WorkerStats",
    "SignalHandler",
    "StopReason",
    # Naaru - Coordinator
    "Naaru",
    "NaaruConfig",
    "NaaruRegion",
    "NaaruMessage",
    "MessageBus",
    "MessageType",
    "AgentResult",
    # Naaru - Workers
    "HarmonicSynthesisWorker",
    "ValidationWorker",
    "AnalysisWorker",
    "MemoryWorker",
    "ExecutiveWorker",
    "ToolRegionWorker",
    "CognitiveRoutingWorker",
    # Naaru - Task Planners
    "TaskPlanner",
    "PlanningError",
    "SelfImprovementPlanner",
    "AgentPlanner",
    "PlanningStrategy",
    "ArtifactPlanner",
    "HarmonicPlanner",
    "CandidateResult",
    "PlanMetrics",
    "PlanMetricsV2",
    "ScoringVersion",
    "VarianceStrategy",
    # Naaru - Persona
    "MURU",
    "NaaruPersona",
    # Naaru - Artifact Types
    "ArtifactSpec",
    "ArtifactGraph",
    "ArtifactLimits",
    "VerificationResult",
    "artifact_to_task",
    "artifacts_to_tasks",
    "select_model_tier",
    "get_model_distribution",
    # Naaru - Artifact Exceptions
    "ArtifactError",
    "CyclicDependencyError",
    "GraphExplosionError",
    "MissingDependencyError",
    "DiscoveryFailedError",
    "ArtifactCreationError",
    # Naaru - Artifact Execution
    "ArtifactExecutor",
    "ArtifactResult",
    "ExecutionResult",
    "ExecutionEvent",
    "execute_artifact_graph",
    "execute_with_discovery",
    # Naaru - Task Graph Analysis
    "ParallelismAnalysis",
    "visualize_task_graph",
    "analyze_parallelism",
    "validate_contracts",
    "format_execution_summary",
    # Naaru - Checkpointing
    "AgentCheckpoint",
    "FailurePolicy",
    "ParallelConfig",
    "TaskExecutionConfig",
    "find_latest_checkpoint",
    "get_checkpoint_path",
    # Naaru - Convergence
    "Convergence",
    "Slot",
    "SlotSource",
    # Naaru - Shards
    "Shard",
    "ShardPool",
    "ShardType",
    # Naaru - Resonance
    "Resonance",
    "ResonanceConfig",
    "ResonanceResult",
    "RefinementAttempt",
    "create_resonance_handler",
    # Naaru - Discernment
    "Discernment",
    "DiscernmentVerdict",
    "DiscernmentResult",
    # Naaru - Model Size
    "ModelSize",
    # Naaru - Diversity Layer
    "Candidate",
    "diversity_none",
    "diversity_sampling",
    "diversity_rotation",
    "diversity_harmonic",
    "HARMONIC_PERSONAS",
    # Naaru - Selection Layer
    "select_passthrough",
    "select_heuristic",
    "select_voting",
    "select_judge",
    # Naaru - Refinement Layer
    "RefinementResult",
    "refine_none",
    "refine_tiered",
    "refine_full",
    # Naaru - Unified Pipeline
    "TaskAnalysis",
    "UnifiedResult",
    "unified_pipeline",
    "select_strategies",
    "create_minimal_config",
    "create_cheap_diversity_config",
    "create_balanced_config",
    "create_quality_config",
    "create_auto_config",
    # Naaru - Plan Persistence
    "SavedExecution",
    "ArtifactCompletion",
    "ExecutionStatus",
    "PlanStore",
    "TraceLogger",
    "hash_goal",
    "hash_content",
    "hash_file",
    "save_execution",
    "get_latest_execution",
    "resume_execution",
    # Naaru - Incremental Execution v2
    "ExecutionCache",
    "ExecutionPlan",
    "IncrementalResult",
    "IncrementalExecutorV2",
    "SkipDecision",
    "SkipReason",
    # Naaru - Integration Verification
    "IntegrationVerifier",
    "StubDetection",
    # Naaru - Modular Components
    "EventEmitter",
    "NaaruEventEmitter",
    "ExecutionCoordinator",
    "LearningExtractor",
    # Skills - Types
    "Skill",
    "SkillDependency",
    "SkillMetadata",
    "SkillType",
    "TrustLevel",
    "Script",
    "Template",
    "Resource",
    "SkillValidation",
    "SkillRetryPolicy",
    "SkillOutput",
    "SkillOutputMetadata",
    "Artifact",
    "SkillResult",
    "SkillError",
    # Skills - Graph
    "SkillGraph",
    "SkillGraphError",
    "CircularDependencyError",
    "MissingDependencyError",
    "UnsatisfiedRequiresError",
    # Skills - Cache
    "SkillCache",
    "SkillCacheKey",
    "SkillCacheEntry",
    # Skills - Compiler
    "SkillCompiler",
    "SkillCompilationCache",
    "SkillCompilationError",
    "CompiledTaskGraph",
    "has_dag_metadata",
    # Skills - Self-Learning
    "SkillLearner",
    "SkillLearningResult",
    "ExecutionPattern",
    "LearnedSkillMetadata",
    "SkillLibrary",
    "SkillProvenance",
    # Skills - Sandbox
    "ScriptSandbox",
    "ScriptResult",
    # Skills - Interop
    "SkillExporter",
    "SkillImporter",
    "validate_skill_folder",
    "SkillValidationResult",
    # Lens
    "LensLibraryEntry",
    "LensManager",
    "DictSerializable",
    "LensIndexEntry",
    "LensLineage",
    "LensManifest",
    "LensVersionInfo",
    "LensIndex",
    "LensIndexManager",
    "add_version_to_manifest",
    "create_lens_manifest",
]
