"""Shared Pydantic models for API routes.

All response models inherit from CamelModel which automatically converts
snake_case Python fields to camelCase in JSON responses.

Run `python scripts/generate_api_types.py` to generate TypeScript types.
"""

from sunwell.interface.server.routes.models.agent import (
    RunCancelResponse,
    RunEventsResponse,
    RunHistoryItem,
    RunItem,
    RunsListResponse,
    RunStartResponse,
    RunStatusResponse,
)
from sunwell.interface.server.routes.models.backlog import (
    BacklogGoalItem,
    BacklogRefreshResponse,
    BacklogResponse,
    GoalAddResponse,
)
from sunwell.interface.server.routes.models.base import (
    CamelModel,
    ErrorResponse,
    SuccessResponse,
)
from sunwell.interface.server.routes.models.briefing import (
    BriefingClearResponse,
    BriefingExistsResponse,
    BriefingResponse,
    BriefingStatus,
)
from sunwell.interface.server.routes.models.coordinator import (
    CoordinatorConflict,
    CoordinatorStateResponse,
    CoordinatorWorker,
    StateDagResponse,
    WorkerActionResponse,
    WorkerStartResponse,
)
from sunwell.interface.server.routes.models.dag import (
    DagAppendResponse,
    DagCheckpointInfo,
    DagEdge,
    DagExecuteResponse,
    DagGoalItem,
    DagGoalResponse,
    DagGoalTaskItem,
    DagIndexResponse,
    DagMetadata,
    DagMilestone,
    DagNode,
    DagPlanCheckpoint,
    DagPlanResponse,
    DagPlanTask,
    DagResponse,
    EnvironmentDagResponse,
    EnvironmentWorkspace,
    WorkspaceDagResponse,
    WorkspaceProjectItem,
)
from sunwell.interface.server.routes.models.indexing import (
    IndexChunk,
    IndexChunkType,
    IndexQueryResponse,
)
from sunwell.interface.server.routes.models.lineage import (
    DependencyGraphResponse,
    FileDependenciesResponse,
    ImpactAnalysisResponse,
    LineageByGoalResponse,
    LineageGraphEdge,
    LineageGraphNode,
    LineageStatsResponse,
    SyncChangesResponse,
    UntrackedChangesResponse,
)
from sunwell.interface.server.routes.models.memory import (
    ColdChunkItem,
    HotChunkItem,
    MemoryCheckpointResponse,
    MemoryChunksResponse,
    MemoryGraphEdge,
    MemoryGraphNode,
    MemoryGraphResponse,
    MemoryGraphStats,
    MemoryResponse,
    MemoryStatsResponse,
    WarmChunkItem,
)
from sunwell.interface.server.routes.models.project import (
    CurrentProjectItem,
    CurrentProjectResponse,
    DefaultProjectItem,
    DefaultProjectResponse,
    MonorepoCheckResponse,
    MonorepoSubProject,
    ProjectAnalysisResponse,
    ProjectArchiveResponse,
    ProjectDeleteResponse,
    ProjectFileEntry,
    ProjectFileResponse,
    ProjectFilesResponse,
    ProjectIntelligenceResponse,
    ProjectIterateResponse,
    ProjectLearningsResponse,
    ProjectRunAnalysisResponse,
    ProjectRunResponse,
    ProjectStatusResponse,
    RecentProjectItem,
    RecentProjectsResponse,
    ResumeProjectResponse,
    ResumeTaskItem,
    ScanProjectsResponse,
    ScannedProjectItem,
    ScannedProjectTask,
)
from sunwell.interface.server.routes.models.prompts import (
    PromptActionResponse,
    SavedPromptItem,
    SavedPromptsResponse,
)
from sunwell.interface.server.routes.models.session import (
    PlanVersionsResponse,
    RecentPlanItem,
    RecentPlansResponse,
    SessionHistoryItem,
    SessionHistoryResponse,
    SessionSummaryResponse,
)
from sunwell.interface.server.routes.models.surface import (
    HomeBlockActionResponse,
    HomePredictPanel,
    HomePredictResponse,
    HomeProcessGoalResponse,
    SurfaceComposeResponse,
    SurfacePrimitive,
    SurfaceRegistryResponse,
)
from sunwell.interface.server.routes.models.workflow import (
    ActiveWorkflowsResponse,
    WorkflowChainItem,
    WorkflowChainsResponse,
    WorkflowExecutionResponse,
    WorkflowRouteResponse,
    WorkflowStatusResponse,
    WorkflowStep,
)
from sunwell.interface.server.routes.models.writer import (
    DiataxisDetection,
    DiataxisResponse,
    DiataxisScores,
    FixAllResponse,
    SkillExecuteResponse,
    ValidationResponse,
    ValidationSeverity,
    ValidationWarning,
)

__all__ = [
    # Base
    "CamelModel",
    # Common
    "SuccessResponse",
    "ErrorResponse",
    # Memory
    "MemoryStatsResponse",
    "MemoryResponse",
    "MemoryCheckpointResponse",
    "HotChunkItem",
    "WarmChunkItem",
    "ColdChunkItem",
    "MemoryChunksResponse",
    "MemoryGraphNode",
    "MemoryGraphEdge",
    "MemoryGraphStats",
    "MemoryGraphResponse",
    # Session
    "SessionSummaryResponse",
    "SessionHistoryItem",
    "SessionHistoryResponse",
    "PlanVersionsResponse",
    "RecentPlanItem",
    "RecentPlansResponse",
    # Project
    "ProjectLearningsResponse",
    "DefaultProjectItem",
    "DefaultProjectResponse",
    "RecentProjectItem",
    "RecentProjectsResponse",
    "ScannedProjectTask",
    "ScannedProjectItem",
    "ScanProjectsResponse",
    "ResumeTaskItem",
    "ResumeProjectResponse",
    "ProjectDeleteResponse",
    "ProjectArchiveResponse",
    "ProjectIterateResponse",
    "MonorepoSubProject",
    "MonorepoCheckResponse",
    "ProjectAnalysisResponse",
    "ProjectFileEntry",
    "ProjectFilesResponse",
    "ProjectRunAnalysisResponse",
    "ProjectRunResponse",
    "ProjectFileResponse",
    "ProjectStatusResponse",
    "ProjectIntelligenceResponse",
    "CurrentProjectItem",
    "CurrentProjectResponse",
    # Briefing
    "BriefingStatus",
    "BriefingResponse",
    "BriefingExistsResponse",
    "BriefingClearResponse",
    # Prompts
    "SavedPromptItem",
    "SavedPromptsResponse",
    "PromptActionResponse",
    # Indexing
    "IndexChunkType",
    "IndexChunk",
    "IndexQueryResponse",
    # Writer
    "ValidationSeverity",
    "ValidationWarning",
    "ValidationResponse",
    "FixAllResponse",
    # DAG
    "DagNode",
    "DagEdge",
    "DagCheckpointInfo",
    "DagMetadata",
    "DagResponse",
    "DagPlanTask",
    "DagPlanCheckpoint",
    "DagPlanResponse",
    "DagGoalItem",
    "DagMilestone",
    "DagIndexResponse",
    "DagGoalTaskItem",
    "DagGoalResponse",
    "WorkspaceProjectItem",
    "WorkspaceDagResponse",
    "EnvironmentWorkspace",
    "EnvironmentDagResponse",
    "DagExecuteResponse",
    "DagAppendResponse",
    # Agent Run
    "RunStartResponse",
    "RunStatusResponse",
    "RunCancelResponse",
    "RunItem",
    "RunsListResponse",
    "RunHistoryItem",
    "RunEventsResponse",
    # Common
    "SuccessResponse",
    "ErrorResponse",
    # Writer/Diataxis
    "DiataxisScores",
    "DiataxisDetection",
    "DiataxisResponse",
    "SkillExecuteResponse",
    # Workflow
    "WorkflowRouteResponse",
    "WorkflowStep",
    "WorkflowExecutionResponse",
    "WorkflowStatusResponse",
    "WorkflowChainItem",
    "WorkflowChainsResponse",
    "ActiveWorkflowsResponse",
    # Backlog
    "BacklogGoalItem",
    "BacklogResponse",
    "GoalAddResponse",
    "BacklogRefreshResponse",
    # Coordinator
    "CoordinatorWorker",
    "CoordinatorConflict",
    "CoordinatorStateResponse",
    "WorkerStartResponse",
    "WorkerActionResponse",
    "StateDagResponse",
    # Lineage
    "LineageByGoalResponse",
    "FileDependenciesResponse",
    "ImpactAnalysisResponse",
    "LineageStatsResponse",
    "UntrackedChangesResponse",
    "SyncChangesResponse",
    "LineageGraphNode",
    "LineageGraphEdge",
    "DependencyGraphResponse",
    # Surface/Home
    "SurfacePrimitive",
    "SurfaceComposeResponse",
    "SurfaceRegistryResponse",
    "HomePredictPanel",
    "HomePredictResponse",
    "HomeProcessGoalResponse",
    "HomeBlockActionResponse",
]
